services:
  postgres:
    image: postgres:15-alpine
    container_name: lucy_realtime_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: realtime_user
      POSTGRES_PASSWORD: realtime_password
      POSTGRES_DB: realtime_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
